### ISSUE TITLE
Any plans to open source MMaterial?

### ISSUE THREAD

**Issue by nuttyartist** [MarkoStanojevic12/markostanojevic12.github.io#1]
Hi! I'm the developer of https://github.com/nuttyartist/notes. I really like what you've done here: https://markostanojevic12.github.io/appMaterialTester.html

Any plans to open-source that? I'd love to integrate it into my app.

Thanks.

**Comment by MarkoStanojevic12** [comment]
Hi! 

I'm very glad you like it! 
Yes, the plan is to make it open source. The reason that it's not open sourced yet is that I'm still not satisfied with what it brings to the table. I don't want to set up any dates, just so I don't disappoint someone.

**Comment by nuttyartist** [comment]
I'm eager to incorporate it into my app, it looks pretty mature to me. What's left to do?

**Comment by kodarn** [comment]
Nice work. Will you be targeting QT 6.5?

**Comment by MarkoStanojevic12** [comment]
@nuttyartist A lot of stuff missing, once released I will be forced to think about backward compatibility or forcing people to create their own forks. Both of which are not to my liking, at least in the early stages.

Biggest things I need to cover are: 
1. Improved icon rendering
2. Think of a way to use opacity masks in Qt6 (want to avoid Qt5 at all costs)
3. Invalid access modifiers ( Didn't think about them when I started, releasing with them would be devastating)

And other little quirks. I would really love to give this out, but it's really not worth it at this stage for the end users.
Thank you for understanding.

**Comment by MarkoStanojevic12** [comment]
@kodarn Currently it's working with QT 6.4, so QT 6.5 should not present too much problems.

**Comment by kodarn** [comment]
Great. Let me know if I can contribute to the project in any way.

**Comment by nuttyartist** [comment]
> @nuttyartist A lot of stuff missing, once released I will be forced to think about backward compatibility or forcing people to create their own forks. Both of which are not to my liking, at least in the early stages.
> 
> Biggest things I need to cover are:
> 
> 1. Improved icon rendering
> 2. Think of a way to use opacity masks in Qt6 (want to avoid Qt5 at all costs)
> 3. Invalid access modifiers ( Didn't think about them when I started, releasing with them would be devastating)
> 
> And other little quirks. I would really love to give this out, but it's really not worth it at this stage for the end users. Thank you for understanding.

Thanks for taking the time to comment. Is it possible that you could at least start release certain components? I like your checkbox look and feel (and its animation) quite a lot and would love to incorporate it into my app. Of course, you'll get credit for it.

**Comment by nuttyartist** [comment]
> @nuttyartist A lot of stuff missing, once released I will be forced to think about backward compatibility or forcing people to create their own forks. Both of which are not to my liking, at least in the early stages.
> 
> Biggest things I need to cover are:
> 
> 1. Improved icon rendering
> 2. Think of a way to use opacity masks in Qt6 (want to avoid Qt5 at all costs)
> 3. Invalid access modifiers ( Didn't think about them when I started, releasing with them would be devastating)
> 
> And other little quirks. I would really love to give this out, but it's really not worth it at this stage for the end users. Thank you for understanding.

Thanks for taking the time to comment. Is it possible that you could at least start release certain components? I like your checkbox look and feel (and its animation) quite a lot and would love to incorporate it into my app. Of course, you'll get credit for it.

**Comment by nuttyartist** [comment]
BTW, I think it would be great if you could support Qt 5 as well. I know it comes with annoyance tho.

**Comment by nuttyartist** [comment]
Hi! Any updates?

**Comment by MarkoStanojevic12** [comment]
@nuttyartist I'm still not satisfied with the current state, but taking the fact that I'm on limited time. I'll create a version 1.0.0 tonight and make it open source. Hopefully some brave individuals will help me along the way to make this module what I aspired it to be. :)

**Comment by nuttyartist** [comment]
That would be super appreciated, thanks! I will try my best to contribute as well.

**Comment by MarkoStanojevic12** [comment]
@nuttyartist It's live
